### ISSUE TITLE
Server doesn't stop

### ISSUE THREAD

**Issue by obelouix** [obelouix/Obelouix-Essential#1]
Server doesn't stop while player do /stop
```[20:21:41] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to ObelouixEssential valpha 1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1125) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_40]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_40]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
	at fr.obelouix.commands.CommandStop.onCommandPreProcess(CommandStop.java:31) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.3.jar:git-Spigot-dbe012b-63e28b1]
	... 16 more```

**Comment by obelouix** [comment]
temporarily disabled World Saving
